var albums = 
[
    {
        "title": "UTOPIA",
        "author": "Travis Scott",
        "cover": "/img/utopia.png",
        "date": "28/07/2023",
        "tracks":[
            "HYAENA",
            "THANK GOD",
            "MODERN JAM",
            "MY EYES",
            "GOD'S COUNTRY",
            "SIRENS",
            "MELTDOWN",
            "FE!N",
            "DELRESTO",
            "I KNOW ?",
            "TOPIA TWINS",
            "CIRCUS MAXIMUS",
            "PARASAIL",
            "SKITZO",
            "LOST FOREVER",
            "LOOOVE",
            "K-POP",
            "TELEKINESIS",
            "TIL FURTHER NOTICE"
        ]
    },
    {
        "title": "Almost Healed",
        "author": "Lil Durk",
        "cover": "/img/almosthealed.jpeg",
        "date": "26/05/2023",
        "tracks":[
            "Therapy Session",
            "Pelle Coat", 
            "All My Life",
            "Never Again",
            "Put Em On Ice",
            "Big Dawg",
            "Never Imagined",
            "Sad Songs",
            "Before Fajr",
            "War Bout It",
            "You Got Em",
            "Grandson",
            "300 Urus",
            "Same Side",
            "B12",
            "At This Point We Stuck",
            "Cross The Globe",
            "Dru Hill",
            "Belt2Ass",
            "Stand By Me",
            "Moment of Truth"
        ]
    },
    {
        "title": "ye",
        "author": "Kanye West",
        "cover": "/img/ye.jpg",
        "date": "01/06/2018",
        "tracks":[
            "I Thought About Killing You",
            "Yikes",
            "All Mine",
            "Wouldn't Leave",
            "No Mistakes",
            "Ghost Town",
            "Violent Crimes"
        ]
    },
    {
        "title": "Pink Tape",
        "author": "Lil Uzi Vert",
        "cover" : "/img/pinktape.png",
        "date":"30/06/2023",
        "tracks":[
            "Flooded The Face",
            "Suicide Doors",
            "Aye",
            "Crush Em",
            "Amped",
            "x2",
            "Died and Came Back",
            "Spin Again",
            "That Fiya",
            "I Gotta",
            "Endless Fashion",
            "Mama, I'm Sorry",
            "All Alone",
            "Nakamura", 
            "Just Wanna Rock",
            "Fire Alarm",
            "CS",
            "Werewolf",
            "Pluto to Mars",
            "Patience",
            "Days Come and Go",
            "Rehab",
            "The End",
            "Zoom",
            "Of Course",
            "Shardai"
        ]
    },
    {
        "title": "Business is Business",
        "author": "Young Thug",
        "cover": "/img/business.png",
        "date":"23/06/2023",
        "tracks":[
            "Parade on Cleveland",
            "Money on The Dresser",
            "Gucci Grocery Bag",
            "Cars Bring Me Out",
            "Wit Da Racks",
            "Uncle M",
            "Abracadabra",
            "Went Thru It",
            "Oh U Went",
            "Want me Dead",
            "Hellcat Kenny",
            "Mad Dog",
            "Jonesboro",
            "Hoodie",
            "Global Access"
        ]
    },
    {
        "title": "a Gift & a Curse",
        "author": "Gunna",
        "cover": "/img/gift.png",
        "date": "16/06/2023",
        "tracks":[
            "back it at",
            "back to the moon",
            "idk nomore",
            "paybach",
            "ca$h $hit",
            "fukumean",
            "rodeo dr",
            "bottom",
            "p angels",
            "born rich",
            "go crazy",
            "bread & butter",
            "turned you back",
            "i was just thinking",
            "alright"
        ]
    },
    {
        "title": "After Hours" , 
        "author": "The Weeknd" ,
        "cover": "/img/afterhours.png" ,
        "date": "20/03/2020" ,
        "tracks": [
               "Blinding Lights",
               "Snowchild",
               "Too Late",
               "Alone Again",
               "Save Your Tears",
               "Scared to Live",
               "In Your Eyes",
               "Until I Bleed Out",
               "Heartless",
               "Repeat After me",
               "Faith",
               "Escape From LA",
               "Hardest to Love",
               "After Hours"
            ]
      } ,
      {
        "title": "Anti" , 
        "author": "Rihanna" ,
        "cover": "/img/anti.png" ,
        "date": "28/01/2016" ,
        "tracks": [
               "Consideration",
               "Work",
               "Sex With Me [explicit]",
               "Never Ending",
               "Yeah, I Said It",
               "Desperado",
               "James Joint",
               "Needed Me",
               "Pose [explicit]",
               "Same OI' Mistakes",
               "Kiss It Better",
               "Close to You",
               "Higher",
               "Goodnight Gotham",
               "Woo",
               "Love on the Brain"
            ]
      } ,
      {
        "title": "whole lotta red" , 
        "author": "Playboi Carti" ,
        "cover": "/img/wlr.png" ,
        "date": "25/12/2020" ,
        "tracks": [
               "Go2DaMoon",
               "Ten x",
               "M3thamorphosis",
               "Punk Monk",
               "Sky",
               "Not PLaying",
               "Sto Breathing",
               "Vamp Anthem",
               "JumpOutTheHouse",
               "On That Time",
               "Beno!",
               "Control",
               "F33I Lik3 Dyin",
               "Over",
               "Die4Guy",
               "ILoveUIHateU",
               "New Tank",
               "Meh",
               "No Sl33p",
               "King Vamp",
               "New N3on",
               "Place",
               "Slay3r",
               "Rockstar Made"
            ]
      } ,
      {
        "title": "HNDRXX" , 
        "author": "Future" ,
        "cover": "/img/hndrxx.jpg" ,
        "date": "24/02/2017" ,
        "tracks": [
               "Comin Out Strong",
               "Selfish",
               "Sorry",
               "Lookin Exotic",
               "Testify",
               "My Collection",
               "Fresh Air",
               "Damage",
               "Neva Missa Lost",
               "Turn on Me",
               "Hallucinating",
               "Solo",
               "Keep Quiet",
               "New Illuminati",
               "Use Me",
               "I Thank U",
               "Incredible"
            ]
      } ,
      {
        "title": "56 nights" , 
        "author": "Future" ,
        "cover": "/img/56nights.jpeg" ,
        "date": "21/03/2015" ,
        "tracks": [
               "Trap Nigs",
               "Da Fam on da Gram Skit",
               "Purple Coming In",
               "56 Nights",
               "Now",
               "No Comprade",
               "March Madness",
               "Never Gon Lose",
               "Diamonds From Africa",
               "Free at Last"
            ]
      } ,
]
var playlist = []
