var albums = 
[
    {
        "title": "UTOPIA",
        "author": "Travis Scott",
        "cover": "/img/utopia.png",
        "date": "28/07/2023",
        "tracks":[
            "HYAENA",
            "THANK GOD",
            "MODERN JAM",
            "MY EYES",
            "GOD'S COUNTRY",
            "SIRENS",
            "MELTDOWN",
            "FE!N",
            "DELRESTO",
            "I KNOW ?",
            "TOPIA TWINS",
            "CIRCUS MAXIMUS",
            "PARASAIL",
            "SKITZO",
            "LOST FOREVER",
            "LOOOVE",
            "K-POP",
            "TELEKINESIS",
            "TIL FURTHER NOTICE"
        ]
    },
    {
        "title": "Almost Healed",
        "author": "Lil Durk",
        "cover": "/img/almosthealed.jpeg",
        "date": "26/05/2023",
        "tracks":[
            "Therapy Session",
            "Pelle Coat", 
            "All My Life",
            "Never Again",
            "Put Em On Ice",
            "Big Dawg",
            "Never Imagined",
            "Sad Songs",
            "Before Fajr",
            "War Bout It",
            "You Got Em",
            "Grandson",
            "300 Urus",
            "Same Side",
            "B12",
            "At This Point We Stuck",
            "Cross The Globe",
            "Dru Hill",
            "Belt2Ass",
            "Stand By Me",
            "Moment of Truth"
        ]
    },
    {
        "title": "ye",
        "author": "Kanye West",
        "cover": "/img/ye.jpg",
        "date": "01/06/2018",
        "tracks":[
            "I Thought About Killing You",
            "Yikes",
            "All Mine",
            "Wouldn't Leave",
            "No Mistakes",
            "Ghost Town",
            "Violent Crimes"
        ]
    },
    {
        "title": "Pink Tape",
        "author": "Lil Uzi Vert",
        "cover" : "/img/pinktape.png",
        "date":"30/06/2023",
        "tracks":[
            "Flooded The Face",
            "Suicide Doors",
            "Aye",
            "Crush Em",
            "Amped",
            "x2",
            "Died and Came Back",
            "Spin Again",
            "That Fiya",
            "I Gotta",
            "Endless Fashion",
            "Mama, I'm Sorry",
            "All Alone",
            "Nakamura", 
            "Just Wanna Rock",
            "Fire Alarm",
            "CS",
            "Werewolf",
            "Pluto to Mars",
            "Patience",
            "Days Come and Go",
            "Rehab",
            "The End",
            "Zoom",
            "Of Course",
            "Shardai"
        ]
    },
    {
        "title": "Business is Business",
        "author": "Young Thug",
        "cover": "/img/business.png",
        "date":"23/06/2023",
        "tracks":[
            "Parade on Cleveland",
            "Money on The Dresser",
            "Gucci Grocery Bag",
            "Cars Bring Me Out",
            "Wit Da Racks",
            "Uncle M",
            "Abracadabra",
            "Went Thru It",
            "Oh U Went",
            "Want me Dead",
            "Hellcat Kenny",
            "Mad Dog",
            "Jonesboro",
            "Hoodie",
            "Global Access"
        ]
    },
    {
        "title": "a Gift & a Curse",
        "author": "Gunna",
        "cover": "/img/gift.png",
        "date": "16/06/2023",
        "tracks":[
            "back it at",
            "back to the moon",
            "idk nomore",
            "paybach",
            "ca$h $hit",
            "fukumean",
            "rodeo dr",
            "bottom",
            "p angels",
            "born rich",
            "go crazy",
            "bread & butter",
            "turned you back",
            "i was just thinking",
            "alright"
        ]
    }
]
